import 'package:latlong2/latlong.dart';
import '../models/parking_spot.dart';
import '../models/accessible_place.dart';

class KrakowDataService {
  /// Krakowskie miejsca postojowe dla osób z niepełnosprawnościami (koperty)
  /// Dane oparte o zasoby miejskie Krakowa (MSIP / ZDMK)
  static final List<ParkingSpot> disabledParkingSpots = [
    // --- STARE MIASTO & DWORZEC GŁÓWNY ---
    const ParkingSpot(
      id: 'krk_park_01',
      street: 'ul. Pawia 5 (Dworzec Główny)',
      district: 'Stare Miasto',
      location: LatLng(50.0668, 19.9464),
      spotsCount: 4,
      isOccupied: false,
      note: 'Dedykowany dojazd do peronów PKP i Galerii Krakowskiej. Winda 20m obok.',
    ),
    const ParkingSpot(
      id: 'krk_park_02',
      street: 'Plac Jana Matejki 8',
      district: 'Kleparz',
      location: LatLng(50.0662, 19.9423),
      spotsCount: 2,
      isOccupied: false,
      note: 'Płaski zjazd na Planty w stronę Barbakanu. Obniżony krawężnik 1.5 cm.',
    ),
    const ParkingSpot(
      id: 'krk_park_03',
      street: 'ul. Szpitalna 15',
      district: 'Stare Miasto',
      location: LatLng(50.0631, 19.9398),
      spotsCount: 2,
      isOccupied: true,
      note: 'Blisko Teatru Słowackiego. Równa nawierzchnia asfaltowa.',
    ),
    const ParkingSpot(
      id: 'krk_park_04',
      street: 'Plac Szczepański 3',
      district: 'Stare Miasto',
      location: LatLng(50.0638, 19.9351),
      spotsCount: 3,
      isOccupied: false,
      note: 'Szeroki wjazd, obniżone krawężniki 1.5 cm, płyta placu bez barier.',
    ),
    const ParkingSpot(
      id: 'krk_park_05',
      street: 'Plac Wszystkich Świętych (Urząd Miasta)',
      district: 'Stare Miasto',
      location: LatLng(50.0589, 19.9382),
      spotsCount: 4,
      isOccupied: false,
      note: 'Pod samym Magistratem. Bezpośredni podjazd windą dla interesantów.',
    ),
    const ParkingSpot(
      id: 'krk_park_06',
      street: 'ul. Podzamcze 2 (Wawel)',
      district: 'Stare Miasto',
      location: LatLng(50.0545, 19.9354),
      spotsCount: 3,
      isOccupied: false,
      note: 'Dojście do Zamku Królewskiego i Centrum Informacji Turystycznej.',
    ),
    const ParkingSpot(
      id: 'krk_park_07',
      street: 'ul. Szeroka 24 (Kazimierz)',
      district: 'Kazimierz',
      location: LatLng(50.0526, 19.9482),
      spotsCount: 2,
      isOccupied: false,
      note: 'Zmodernizowana nawierzchnia, obniżone krawężniki przy synagodze.',
    ),
    const ParkingSpot(
      id: 'krk_park_08',
      street: 'Plac Wolnica 1',
      district: 'Kazimierz',
      location: LatLng(50.0489, 19.9442),
      spotsCount: 3,
      isOccupied: false,
      note: 'Równa nawierzchnia płytowa, bez barier architektonicznych.',
    ),
    const ParkingSpot(
      id: 'krk_park_09',
      street: 'ul. Poselska 10',
      district: 'Stare Miasto',
      location: LatLng(50.0581, 19.9365),
      spotsCount: 1,
      isOccupied: false,
      note: 'Koperta przy Muzeum Archeologicznym, dojście do Plant.',
    ),
    const ParkingSpot(
      id: 'krk_park_10',
      street: 'ul. Basztowa 20',
      district: 'Kleparz',
      location: LatLng(50.0674, 19.9405),
      spotsCount: 2,
      isOccupied: false,
      note: 'Przy Urzędzie Wojewódzkim. Podjazd przystosowany pod vany z rampą.',
    ),
    const ParkingSpot(
      id: 'krk_park_11',
      street: 'ul. Pijarska 1 / Floriańska',
      district: 'Stare Miasto',
      location: LatLng(50.0649, 19.9412),
      spotsCount: 2,
      isOccupied: false,
      note: 'Tuż przy Bramie Floriańskiej i Muzeum Czartoryskich. Gładkie płyty granitowe.',
    ),
    const ParkingSpot(
      id: 'krk_park_12',
      street: 'ul. Karmelicka 12 (Teatr Bagatela)',
      district: 'Piasek',
      location: LatLng(50.0639, 19.9315),
      spotsCount: 2,
      isOccupied: true,
      note: 'Szeroka koperta 3.6m z wyznaczonym polem bezpieczeństwa dla wózków inwalidzkich.',
    ),
    const ParkingSpot(
      id: 'krk_park_13',
      street: 'ul. Straszewskiego 17 (Radisson Blu / Filharmonia)',
      district: 'Stare Miasto',
      location: LatLng(50.0577, 19.9328),
      spotsCount: 3,
      isOccupied: false,
      note: 'Bezpośrednio naprzeciwko wejścia do hotelu Radisson Blu i Filharmonii Krakowskiej.',
    ),
    const ParkingSpot(
      id: 'krk_park_14',
      street: 'ul. Powiśle 7 (Sheraton Grand)',
      district: 'Stare Miasto',
      location: LatLng(50.0536, 19.9318),
      spotsCount: 3,
      isOccupied: false,
      note: 'Płaski podjazd pod hotel Sheraton, bezprogowe wejście na Bulwary Wiślane.',
    ),
    const ParkingSpot(
      id: 'krk_park_15',
      street: 'al. 3 Maja 1 (Gmach Główny Muzeum Narodowego)',
      district: 'Krowodrza',
      location: LatLng(50.0604, 19.9238),
      spotsCount: 4,
      isOccupied: false,
      note: 'Przy samej rampie muzealnej MNK i alei spacerowej w stronę Błoń.',
    ),
    const ParkingSpot(
      id: 'krk_park_16',
      street: 'al. Mickiewicza 30 (AGH Budynek Główny)',
      district: 'Krowodrza',
      location: LatLng(50.0660, 19.9198),
      spotsCount: 4,
      isOccupied: false,
      note: 'Dedykowane koperty z obniżonym krawężnikiem 1 cm i windą zewnętrzną AGH.',
    ),
    const ParkingSpot(
      id: 'krk_park_17',
      street: 'ul. Rajska 1 (Wojewódzka Biblioteka Publiczna)',
      district: 'Piasek',
      location: LatLng(50.0644, 19.9315),
      spotsCount: 2,
      isOccupied: false,
      note: 'Zjazd bezpośrednio na płaski dziedziniec WBP i Małopolskiego Ogrodu Sztuki.',
    ),
    const ParkingSpot(
      id: 'krk_park_18',
      street: 'ul. Czarnowiejska 36',
      district: 'Nowa Wieś',
      location: LatLng(50.0667, 19.9142),
      spotsCount: 2,
      isOccupied: false,
      note: 'Blisko Miasteczka Studenckiego AGH, podjazd o łagodnym nachyleniu 4%.',
    ),
    const ParkingSpot(
      id: 'krk_park_19',
      street: 'ul. Długa 15 (Nowy Kleparz)',
      district: 'Kleparz',
      location: LatLng(50.0682, 19.9366),
      spotsCount: 2,
      isOccupied: true,
      note: 'Gładka nawierzchnia asfaltowa, blisko apteki całodobowej i przystanków.',
    ),
    const ParkingSpot(
      id: 'krk_park_20',
      street: 'ul. Józefa 22 (Kazimierz - Stara Synagoga)',
      district: 'Kazimierz',
      location: LatLng(50.0508, 19.9475),
      spotsCount: 2,
      isOccupied: false,
      note: 'Wyrównany pas jezdni bez wystającej kostki, obniżone zjazdy na chodnik.',
    ),
    const ParkingSpot(
      id: 'krk_park_21',
      street: 'ul. Halicka 14 (PURO Kazimierz)',
      district: 'Kazimierz',
      location: LatLng(50.0518, 19.9495),
      spotsCount: 2,
      isOccupied: false,
      note: 'Przy wejściu bez barier hotelu PURO Kazimierz, krawężnik zlicowany z jezdnią.',
    ),
    const ParkingSpot(
      id: 'krk_park_22',
      street: 'ul. Nadwiślańska 4 (Cricoteka)',
      district: 'Podgórze',
      location: LatLng(50.0454, 19.9528),
      spotsCount: 3,
      isOccupied: false,
      note: 'Przy samym wejściu do Cricoteki i Kładce Ojca Bernatka. Równy deptak.',
    ),
    const ParkingSpot(
      id: 'krk_park_23',
      street: 'Plac Bohaterów Getta 2 (Apteka pod Orłem)',
      district: 'Podgórze',
      location: LatLng(50.0468, 19.9548),
      spotsCount: 3,
      isOccupied: false,
      note: 'Płytowa, bezprogowa nawierzchnia, bezpośredni dostęp do Muzeum i tramwaju.',
    ),
    const ParkingSpot(
      id: 'krk_park_24',
      street: 'ul. Lipowa 4 (MOCAK / Fabryka Schindlera)',
      district: 'Zabłocie',
      location: LatLng(50.0475, 19.9612),
      spotsCount: 4,
      isOccupied: false,
      note: 'Dedykowany parking bezpośrednio przed wejściem do MOCAK i Muzeum Schindlera.',
    ),
    const ParkingSpot(
      id: 'krk_park_25',
      street: 'ul. Marii Konopnickiej 17 (ICE Kraków)',
      district: 'Dębniki',
      location: LatLng(50.0484, 19.9315),
      spotsCount: 6,
      isOccupied: false,
      note: 'Strefa Kiss&Ride bez barier oraz winda bezpośrednia z parkingu podziemnego ICE.',
    ),
    const ParkingSpot(
      id: 'krk_park_26',
      street: 'ul. Lubicz 23 (Rondo Mogilskie)',
      district: 'Grzegórzki',
      location: LatLng(50.0655, 19.9560),
      spotsCount: 3,
      isOccupied: false,
      note: 'Bezpośredni zjazd przeszkloną windą miejską do dolnego poziomu peronów MPK.',
    ),
    const ParkingSpot(
      id: 'krk_park_27',
      street: 'Plac Jana Nowaka-Jeziorańskiego (Pawia / Dworzec)',
      district: 'Stare Miasto',
      location: LatLng(50.0658, 19.9452),
      spotsCount: 4,
      isOccupied: false,
      note: 'Podjazd z poziomu 0 do Hali Głównej Dworca i punktu asysty osób niepełnosprawnych.',
    ),
    const ParkingSpot(
      id: 'krk_park_28',
      street: 'ul. Stanisława Lema 7 (Tauron Arena Kraków)',
      district: 'Czyżyny',
      location: LatLng(50.0680, 19.9910),
      spotsCount: 8,
      isOccupied: false,
      note: 'Szerokie zatoki z oznakowaniem LED, bezpośredni bezbarierowy wjazd do wind areny.',
    ),
    const ParkingSpot(
      id: 'krk_park_29',
      street: 'ul. Kopernika 15 (Centrum Medyczne UJ)',
      district: 'Wesoła',
      location: LatLng(50.0632, 19.9505),
      spotsCount: 3,
      isOccupied: true,
      note: 'Zatoka z rampą łagodną do wejścia klinicznego, asysta portierska.',
    ),
    const ParkingSpot(
      id: 'krk_park_30',
      street: 'al. Pokoju 5 (Teatr Variete)',
      district: 'Grzegórzki',
      location: LatLng(50.0592, 19.9654),
      spotsCount: 2,
      isOccupied: false,
      note: 'Obniżony krawężnik 1 cm, równy chodnik betonowy prowadzący do wejścia teatru.',
    ),
    const ParkingSpot(
      id: 'krk_park_31',
      street: 'ul. Podgórska 34 (Galeria Kazimierz)',
      district: 'Grzegórzki',
      location: LatLng(50.0538, 19.9567),
      spotsCount: 5,
      isOccupied: false,
      note: 'Koperty na poziomie ulicy pod zadaszeniem, automatyczne drzwi obrotowe z opcją slow.',
    ),
    const ParkingSpot(
      id: 'krk_park_32',
      street: 'ul. Henryka Kamieńskiego 11 (Bonarka)',
      district: 'Podgórze Duchackie',
      location: LatLng(50.0278, 19.9575),
      spotsCount: 6,
      isOccupied: false,
      note: 'Koperty XXL z poszerzonym pasem dla wind samochodowych, wejście z poziomu 0.',
    ),
    const ParkingSpot(
      id: 'krk_park_33',
      street: 'Plac Wszystkich Świętych 11 (Franciszkańska)',
      district: 'Stare Miasto',
      location: LatLng(50.0592, 19.9368),
      spotsCount: 2,
      isOccupied: false,
      note: 'Gładkie płyty granitowe, dojście bezprogowe do Bazyliki Franciszkanów i Plant.',
    ),
    const ParkingSpot(
      id: 'krk_park_34',
      street: 'ul. Kanonicza 18 (Wawel / Muzeum Archidiecezjalne)',
      district: 'Stare Miasto',
      location: LatLng(50.0558, 19.9372),
      spotsCount: 1,
      isOccupied: false,
      note: 'Koperta w zabytkowej strefie z wyrównanym dojazdem płytowym.',
    ),
    const ParkingSpot(
      id: 'krk_park_35',
      street: 'ul. Reymonta 22 (Park Jordana / Stadion Miejski)',
      district: 'Krowodrza',
      location: LatLng(50.0632, 19.9095),
      spotsCount: 4,
      isOccupied: false,
      note: 'Szerokie miejsca przy wejściu do Parku Jordana, łagodne zjazdy na alejki parkowe.',
    ),
  ];

  /// Hotele oraz budynki użyteczności i kultury z certyfikowaną dostępnością
  /// wraz z linkami do ich oficjalnych stron, social mediów i kontaktu.
  static final List<AccessiblePlace> accessiblePlaces = [
    // =========================================================================
    // HOTELE Z TRYBEM DLA OSÓB Z NIEPEŁNOSPRAWNOŚCIAMI
    // =========================================================================
    const AccessiblePlace(
      id: 'place_hotel_radisson',
      name: 'Radisson Blu Hotel Kraków',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Hotel z certyfikatem bez barier',
      categoryLabelEn: 'Accessible Certified Hotel',
      address: 'ul. Straszewskiego 17, 31-101 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0578, 19.9329),
      accessibilityScore: 98,
      descriptionPl:
          'Ekskluzywny hotel tuż przy Plantach i Zamku Królewskim na Wawelu. Posiada certyfikat pełnej dostępności architektonicznej, dedykowane pokoje z prysznicami bezprogowymi (roll-in), pętlę indukcyjną w recepcji oraz automatyczne drzwi wejściowe.',
      descriptionEn:
          'Upscale hotel right next to Planty Park and Wawel Castle. Fully accessible with roll-in shower adapted rooms, reception hearing loop, wide doors, and audio-guided elevators.',
      accessibilityHighlightsPl: [
        'Pokoje w 100% przystosowane z prysznicem bezprogowym i uchwytami',
        'Wejście z poziomu 0 (automatyczne drzwi przesuwne)',
        'Windy z komunikatami głosowymi i alfabetem Braille’a',
        'Pętla indukcyjna dla aparatów słuchowych w recepcji',
        'Obsługa przeszkolona z asysty osób z niepełnosprawnościami',
        'Pies asystujący / przewodnik w pełni akceptowany',
        'Dedykowane podziemne koperty parkingowe z windą na piętra',
      ],
      accessibilityHighlightsEn: [
        '100% adapted accessible rooms with roll-in shower & support rails',
        'Zero-step entrance with automatic sliding doors',
        'Elevators with voice synthesizer & Braille buttons',
        'Hearing induction loop at front desk',
        'Staff trained in special mobility assistance',
        'Service and guide dogs warmly welcomed',
        'Reserved indoor accessible parking with elevator access',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.radissonhotels.com/pl-pl/hotele/radisson-blu-krakow',
      instagramUrl: 'https://www.instagram.com/radissonblukrakow/',
      instagramHandle: '@radissonblukrakow',
      facebookUrl: 'https://www.facebook.com/RadissonBluKrakow',
      facebookName: 'Radisson Blu Hotel Krakow',
      phoneNumber: '+48 12 618 88 88',
    ),

    const AccessiblePlace(
      id: 'place_hotel_sheraton',
      name: 'Sheraton Grand Kraków',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Luksusowy hotel bez barier',
      categoryLabelEn: 'Luxury Accessible Hotel',
      address: 'ul. Powiśle 7, 31-101 Kraków',
      district: 'Stare Miasto / Zakole Wisły',
      location: LatLng(50.0535, 19.9320),
      accessibilityScore: 97,
      descriptionPl:
          'Położony nad brzegiem Wisły u stóp Wawelu. Oferuje pokoje Accessible King z ergonomicznym umeblowaniem, obniżonymi włącznikami, basen z hydraulicznym podnośnikiem dla osób na wózkach oraz łagodne rampy zjazdowe.',
      descriptionEn:
          'Located on the Vistula River bank beneath Wawel Hill. Features Accessible King suites, indoor pool with disabled hydraulic lift, and ramped access throughout all venues.',
      accessibilityHighlightsPl: [
        'Pokoje Accessible King z przestrzenią manewrową 1.8 m',
        'Basen hotelowy z hydraulicznym podnośnikiem dla wózków',
        'Łagodne rampy zjazdowe (nachylenie poniżej 5%)',
        'Obniżona lada recepcyjna i stanowisko szybkiego meldunku',
        'Pętle indukcyjne w salach konferencyjnych i recepcji',
        'Łazienki z alarmem przyzywowym SOS',
      ],
      accessibilityHighlightsEn: [
        'Accessible King rooms with 1.8m turning wheelchair radius',
        'Indoor heated swimming pool with hydraulic disabled chair lift',
        'Gentle access ramps (under 5% grade)',
        'Lowered reception check-in desk',
        'Hearing loops in conference halls and lobby',
        'Emergency bathroom SOS cords',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.marriott.com/en-us/hotels/krksi-sheraton-grand-krakow',
      instagramUrl: 'https://www.instagram.com/sheratongrandkrakow/',
      instagramHandle: '@sheratongrandkrakow',
      facebookUrl: 'https://www.facebook.com/SheratonGrandKrakow',
      facebookName: 'Sheraton Grand Krakow',
      phoneNumber: '+48 12 662 10 00',
    ),

    const AccessiblePlace(
      id: 'place_hotel_puro_stare_miasto',
      name: 'PURO Hotel Kraków Stare Miasto',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Nowoczesny hotel bez barier',
      categoryLabelEn: 'Modern Accessible Hotel',
      address: 'ul. Ogrodowa 10, 31-155 Kraków',
      district: 'Stare Miasto / Dworzec',
      location: LatLng(50.0678, 19.9442),
      accessibilityScore: 96,
      descriptionPl:
          'Stylowy, nowoczesny hotel 150m od Dworca Głównego. Posiada całkowicie płaskie wejścia, pokoje dostosowane ze sterowaniem dotykowym i świetlną sygnalizacją dla osób niesłyszących oraz restaurację bez progów.',
      descriptionEn:
          'Boutique modern hotel next to Kraków Główny Station. Step-free design, smart adapted rooms with optical doorbells for deaf guests, and accessible dining.',
      accessibilityHighlightsPl: [
        '100% obiekt bezprogowy (poziom 0 od ulicy do pokoi)',
        'Sygnalizacja świetlna i wibracyjna budzika dla niesłyszących',
        'Kabiny prysznicowe typu walk-in ze składanymi siedziskami',
        'Restauracja i kawiarnia HINT z szerokimi alejkami',
        'Dotykowy system meldunku i dedykowana asysta personelu',
      ],
      accessibilityHighlightsEn: [
        '100% threshold-free design from sidewalk to suites',
        'Flashing light and vibrating alert system for hearing impaired',
        'Walk-in showers with wall-mounted fold-down seats',
        'HINT Restaurant with wide accessible aisles',
        'Self check-in kiosks + dedicated personal assistant',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: false,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://purohotel.pl/krakow-stare-miasto',
      instagramUrl: 'https://www.instagram.com/purohotels/',
      instagramHandle: '@purohotels',
      facebookUrl: 'https://www.facebook.com/purohotelkrakow',
      facebookName: 'PURO Hotel Krakow',
      phoneNumber: '+48 12 314 21 00',
    ),

    const AccessiblePlace(
      id: 'place_hotel_stary',
      name: 'Hotel Stary (Zabytkowy obiekt bez barier)',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Zabytkowy hotel z windą',
      categoryLabelEn: 'Historic Boutique Hotel',
      address: 'ul. Szczepańska 5, 31-011 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0628, 19.9362),
      accessibilityScore: 93,
      descriptionPl:
          'Wyjątkowe połączenie XIV-wiecznej architektury z nowoczesną dostępnością. Przeszklona winda łączy wszystkie poziomy, a pokoje przystosowane oferują udogodnienia bez naruszania historycznego uroku kamienicy.',
      descriptionEn:
          '14th-century merchant tenement converted into an accessible 5-star hotel with panoramic elevator, wide room entrances, and zero-barrier rooftop terrace.',
      accessibilityHighlightsPl: [
        'Nowoczesna winda panoramiczna na wszystkie piętra i taras',
        'Pokoje ze specjalnie zaprojektowanymi szerokimi łazienkami',
        'Asysta konsjerża przy wejściu od strony Rynku',
        'Strefa basenowa i wellness z rampą łagodnego zejścia',
      ],
      accessibilityHighlightsEn: [
        'Modern panoramic elevator servicing all guest floors & roof',
        'Specially adapted suites with wide accessible bathrooms',
        'Concierge curb assistance from Market Square',
        'Wellness & ancient cellar pool with ramp access',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: false,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: false,
      websiteUrl: 'https://stary.hotel.com.pl/',
      instagramUrl: 'https://www.instagram.com/hotelstary/',
      instagramHandle: '@hotelstary',
      facebookUrl: 'https://www.facebook.com/hotelstary',
      facebookName: 'Hotel Stary Kraków',
      phoneNumber: '+48 12 384 08 08',
    ),

    const AccessiblePlace(
      id: 'place_hotel_mercure',
      name: 'Mercure Kraków Stare Miasto',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Hotel przy Dworcu z trybem ON',
      categoryLabelEn: 'Transit Hub Accessible Hotel',
      address: 'ul. Pawia 18b, 31-154 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0692, 19.9460),
      accessibilityScore: 97,
      descriptionPl:
          'Zlokalizowany tuż obok peronów kolejowych i Dworca Autobusowego. Pokoje "Special Needs" z szerokimi przejściami, oznakowaniem w alfabecie Braille’a w windach i bezprogowym wejściem prosto z poziomu chodnika.',
      descriptionEn:
          'Prime transit location right by train platforms. Special Needs rooms with roll-in facilities, Braille touchpoints, and seamless street-level access.',
      accessibilityHighlightsPl: [
        'Pokoje "Special Needs" w pełni zgodne ze standardem Accor All',
        'Bezpośredni płaski łącznik z peronami Dworca Głównego',
        'System Braille’a w windach i na korytarzach hotelowych',
        'Sygnalizatory bezpieczeństwa SOS w łazienkach',
        'Podziemny parking z dedykowanymi kopertami i szeroką windą',
      ],
      accessibilityHighlightsEn: [
        'Accor "All Access" certified adapted guest rooms',
        'Direct flat walkway from main train platforms',
        'Braille signage across lifts and corridors',
        'Emergency bathroom alarms connected to 24/7 reception',
        'Underground parking with oversized disabled bays and lift',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://all.accor.com/hotel/9627/index.pl.shtml',
      instagramUrl: 'https://www.instagram.com/mercurekrakowstaremiasto/',
      instagramHandle: '@mercurekrakowstaremiasto',
      facebookUrl: 'https://www.facebook.com/MercureKrakowStareMiasto',
      facebookName: 'Mercure Krakow Stare Miasto',
      phoneNumber: '+48 12 225 11 11',
    ),

    const AccessiblePlace(
      id: 'place_hotel_puro_kazimierz',
      name: 'PURO Kraków Kazimierz',
      category: AccessiblePlaceCategory.hotel,
      categoryLabelPl: 'Hotel bez barier na Kazimierzu',
      categoryLabelEn: 'Accessible Hotel Kazimierz',
      address: 'ul. Halicka 14a, 31-036 Kraków',
      district: 'Kazimierz',
      location: LatLng(50.0520, 19.9498),
      accessibilityScore: 96,
      descriptionPl:
          'Nowo wybudowany obiekt w sercu żydowskiego Kazimierza. Brak progów, ogród hotelowy dostępny dla wózków, pętla indukcyjna, menu w alfabecie Braille’a w piekarni MAK Bread&Coffee.',
      descriptionEn:
          'Contemporary hotel in historic Kazimierz. Zero barriers throughout, accessible landscaped courtyard, hearing loops, and Braille menus at the on-site artisanal bakery.',
      accessibilityHighlightsPl: [
        'Brak barier od ulicy aż po wewnętrzny ogród relaksu',
        'Pokoje z prysznicami bez brodzików i drzwiami 95 cm',
        'Pętla indukcyjna w recepcji i sali konferencyjnej',
        'Menu w alfabecie Braille’a w kawiarni i restauracji',
        'Darmowy wstęp dla certyfikowanych psów asystujących',
      ],
      accessibilityHighlightsEn: [
        'Zero thresholds from the street into the courtyard gardens',
        'Roll-in shower suites with wide 95cm doorways',
        'Induction loops at reception & conference spaces',
        'Braille food and beverage menus',
        'Free stay and welcome amenities for service dogs',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: true,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://purohotel.pl/krakow-kazimierz',
      instagramUrl: 'https://www.instagram.com/purohotels/',
      instagramHandle: '@purohotels',
      facebookUrl: 'https://www.facebook.com/purohotelkrakowkazimierz',
      facebookName: 'PURO Krakow Kazimierz',
      phoneNumber: '+48 12 889 90 00',
    ),

    // =========================================================================
    // BUDYNKI UŻYTECZNOŚCI PUBLICZNEJ, KULTURY I ATRAKCJE BEZ BARIER
    // =========================================================================
    const AccessiblePlace(
      id: 'place_ice_krakow',
      name: 'Centrum Kongresowe ICE Kraków',
      category: AccessiblePlaceCategory.publicBuilding,
      categoryLabelPl: 'Lider dostępności architektonicznej',
      categoryLabelEn: 'Leading Accessible Convention Center',
      address: 'ul. Marii Konopnickiej 17, 30-302 Kraków',
      district: 'Dębniki',
      location: LatLng(50.0483, 19.9312),
      accessibilityScore: 100,
      descriptionPl:
          'Zwycięzca nagrody "Kraków bez Barier". Jeden z najbardziej dostępnych obiektów widowiskowo-kongresowych w Europie: stałe pętle indukcyjne we wszystkich salach audytoryjnych, 7 wind wielkogabarytowych i 12 kopert parkingowych.',
      descriptionEn:
          'Winner of the "Kraków Without Barriers" Grand Prix. State-of-the-art accessibility with fixed hearing induction loops across all auditoriums, 7 panoramic high-capacity lifts, and dedicated wheelchair platforms.',
      accessibilityHighlightsPl: [
        'Stałe pętle indukcyjne we wszystkich salach audytoryjnych i foyer',
        '7 wind wielkogabarytowych z komunikatami głosowymi w 3 językach',
        'Dedykowane podesty dla wózków z doskonałą linią wzroku na scenę',
        'Dostępne toalety z przewijakami dla dorosłych (tzw. komfortki)',
        'Strefa Kiss&Ride bez barier oraz 12 kopert parkingowych w garażu',
        'Dostępny tłumacz Polskiego Języka Migowego (PJM) na wydarzeniach',
      ],
      accessibilityHighlightsEn: [
        'Fixed induction hearing loops throughout all halls and foyers',
        '7 oversized lifts with trilingual audio announcements',
        'Dedicated wheelchair viewing platforms with unobstructed stage sightlines',
        'Accessible restrooms with adult changing tables ("komfortka")',
        'Barrier-free Kiss & Ride bay and 12 reserved parking spaces',
        'Polish Sign Language (PJM) interpretation available for events',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://icekrakow.pl/',
      instagramUrl: 'https://www.instagram.com/icekrakow/',
      instagramHandle: '@icekrakow',
      facebookUrl: 'https://www.facebook.com/ICEKrakow',
      facebookName: 'ICE Kraków Congress Centre',
      phoneNumber: '+48 12 354 25 00',
    ),

    const AccessiblePlace(
      id: 'place_mnk_gmach_glowny',
      name: 'Muzeum Narodowe w Krakowie - Gmach Główny',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Muzeum bez barier',
      categoryLabelEn: 'Accessible National Museum',
      address: 'al. 3 Maja 1, 30-062 Kraków',
      district: 'Krowodrza / Błonia',
      location: LatLng(50.0602, 19.9234),
      accessibilityScore: 98,
      descriptionPl:
          'Główna siedziba MNK. Posiada zewnętrzną rampę podjazdową, windy do wszystkich galerii (XX+XXI wiek, rzemiosło), wózki inwalidzkie do bezpłatnego wypożyczenia w szatni, tyflografiki dotykowe oraz audiodeskrypcję dla osób niewidomych.',
      descriptionEn:
          'Flagship building of the National Museum in Kraków. Features outdoor wheelchair ramp, lifts to all permanent exhibition galleries, tactile models, complimentary loaner wheelchairs, and audio description.',
      accessibilityHighlightsPl: [
        'Zewnętrzna rampa podjazdowa o łagodnym spadku z al. 3 Maja',
        'Windy z syntezą mowy obsługujące wszystkie galerie wystawowe',
        'Darmowe wypożyczenie wózków inwalidzkich w szatni głównej',
        'Tyflograficzne makiety dotykowe najsłynniejszych dzieł sztuki',
        'Pętla indukcyjna w kasie biletowej i audytorium',
        'Specjalne ścieżki zwiedzania z audiodeskrypcją',
      ],
      accessibilityHighlightsEn: [
        'Low-incline ramp leading to automatic entrance doors',
        'Voice-guided elevators serving every gallery level',
        'Free loan of wheelchairs at cloakroom',
        'Tactile 3D graphics and models for visually impaired',
        'Hearing induction loop at ticket desk & auditorium',
        'Curated audio-described tours for sight-impaired visitors',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://mnk.pl/oddzial/gmach-glowny',
      instagramUrl: 'https://www.instagram.com/mnkrakow/',
      instagramHandle: '@mnkrakow',
      facebookUrl: 'https://www.facebook.com/mnkrakow',
      facebookName: 'Muzeum Narodowe w Krakowie',
      phoneNumber: '+48 12 433 55 00',
    ),

    const AccessiblePlace(
      id: 'place_sukiennice_mnk',
      name: 'Sukiennice - Galeria Sztuki Polskiej XIX w.',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Zabytkowa galeria z windą',
      categoryLabelEn: 'Historic Cloth Hall Gallery',
      address: 'Rynek Główny 1, 31-042 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0617, 19.9373),
      accessibilityScore: 95,
      descriptionPl:
          'Zabytkowe serce Krakowa. W podcieniach Sukiennic znajduje się dyskretna winda przystosowana dla wózków, która prowadzi prosto na piętro ekspozycji. Sale są bezprogowe, dostępne są tyflografiki dotykowe i audioprzewodniki.',
      descriptionEn:
          'Iconic Cloth Hall on Kraków Main Market Square. Features a specialized lift in the arcades to upper galleries, threshold-free floors, audio guides with hearing loop, and tactile models.',
      accessibilityHighlightsPl: [
        'Dedykowana winda dla wózków w arkadach Sukiennic (od strony kościoła Mariackiego)',
        'Całkowicie bezprogowe, równe parkiety we wszystkich 4 salach wystawowych',
        'Dotykowa makieta obrazu "Szał uniesień" Władysława Podkowińskiego',
        'Audioprzewodniki kompatybilne z aparatami słuchowymi (T-coil)',
        'Przeszkolona asysta muzealna na żądanie',
      ],
      accessibilityHighlightsEn: [
        'Dedicated wheelchair lift in the arcades near St. Mary Basilica',
        'Completely flat, seamless wooden floors across all 4 exhibition halls',
        'Tactile relief model of Podkowiński’s masterpiece "Frenzy of Exultations"',
        'T-coil hearing loop enabled audio guides',
        'Trained museum assistants available on request',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: false,
      websiteUrl: 'https://mnk.pl/oddzial/sukiennice',
      instagramUrl: 'https://www.instagram.com/mnkrakow/',
      instagramHandle: '@mnkrakow',
      facebookUrl: 'https://www.facebook.com/mnkrakow',
      facebookName: 'Muzeum Narodowe w Krakowie - Sukiennice',
      phoneNumber: '+48 12 433 54 00',
    ),

    const AccessiblePlace(
      id: 'place_mocak',
      name: 'MOCAK - Muzeum Sztuki Współczesnej',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Nowoczesne muzeum bez barier',
      categoryLabelEn: 'Contemporary Art Museum',
      address: 'ul. Lipowa 4, 30-702 Kraków',
      district: 'Zabłocie',
      location: LatLng(50.0474, 19.9609),
      accessibilityScore: 99,
      descriptionPl:
          'Zwycięzca plebiscytu "Kraków bez Barier". Przestronna, industrialna architektura bez ani jednego stopnia w głównych ciągach komunikacyjnych, przeszklone windy, pętla indukcyjna oraz dedykowany program warsztatów sensorycznych.',
      descriptionEn:
          'Award-winning contemporary art museum on the former Oskar Schindler factory grounds. Completely step-free circulation, panoramic elevators, induction loops, and sensory tours.',
      accessibilityHighlightsPl: [
        '100% płaska przestrzeń ekspozycyjna z podłogami z polerowanego betonu',
        'Szerokie windy przeszklone łączące wszystkie poziomy i kawiarnię',
        'Pętle indukcyjne w kasach, księgarni i sali audiowizualnej',
        'Możliwość zwiedzania z psem asystującym i miski z wodą',
        '4 dedykowane koperty parkingowe tuż obok bramy wejściowej',
      ],
      accessibilityHighlightsEn: [
        '100% step-free gallery space with polished flat concrete floors',
        'Wide glass elevators connecting galleries, bookstore, and cafe',
        'Hearing induction loops at ticketing and cinema hall',
        'Service dogs welcomed with resting spots and water bowls',
        '4 reserved accessible parking spaces adjacent to museum entrance',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://mocak.pl/',
      instagramUrl: 'https://www.instagram.com/mocak_krakow/',
      instagramHandle: '@mocak_krakow',
      facebookUrl: 'https://www.facebook.com/mocakkrakow',
      facebookName: 'MOCAK Muzeum Sztuki Wspolczesnej w Krakowie',
      phoneNumber: '+48 12 263 40 00',
    ),

    const AccessiblePlace(
      id: 'place_teatr_slowackiego',
      name: 'Teatr im. Juliusza Słowackiego w Krakowie',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Zabytkowy teatr z platformą',
      categoryLabelEn: 'Historic Opera & Theatre',
      address: 'Plac Świętego Ducha 1, 31-023 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0638, 19.9427),
      accessibilityScore: 94,
      descriptionPl:
          'Zabytkowy gmach teatru z 1893 roku zmodernizowany z poszanowaniem dostępności. Wejście boczne z podnośnikiem platformowym, dedykowane miejsca dla osób na wózkach na parterze, spektakle z audiodeskrypcją i pętlą indukcyjną.',
      descriptionEn:
          'Historic 19th-century theatre adapted with platform lifts, wheelchair stall spaces, audio description headsets, and induction loops for stage performances.',
      accessibilityHighlightsPl: [
        'Platforma windowa przy wejściu bocznym od strony Plant',
        'Specjalne fotele i strefy dla wózków inwalidzkich na widowni parteru',
        'Spektakle z audiodeskrypcją dla niewidomych i napisami dla niesłyszących',
        'System słuchawkowy ze wzmocnieniem akustycznym',
        'Dostosowana toaleta z automatycznym otwieraniem',
      ],
      accessibilityHighlightsEn: [
        'Platform lift entrance from the Planty Park side',
        'Dedicated wheelchair seating in prime parquet tier',
        'Regular performances with audio description and closed captions',
        'FM assistive listening headset system',
        'Fully accessible restroom with automated door assist',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: false,
      websiteUrl: 'https://teatrwkrakowie.pl/',
      instagramUrl: 'https://www.instagram.com/teatrslowackiego/',
      instagramHandle: '@teatrslowackiego',
      facebookUrl: 'https://www.facebook.com/teatrwkrakowie',
      facebookName: 'Teatr im. Juliusza Slowackiego w Krakowie',
      phoneNumber: '+48 12 424 45 25',
    ),

    const AccessiblePlace(
      id: 'place_cricoteka',
      name: 'Cricoteka - Ośrodek Twórczości Tadeusza Kantora',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Nowatorska architektura bez barier',
      categoryLabelEn: 'Art Centre & Museum Cricoteka',
      address: 'ul. Nadwiślańska 2-4, 30-527 Kraków',
      district: 'Podgórze',
      location: LatLng(50.0453, 19.9525),
      accessibilityScore: 98,
      descriptionPl:
          'Spektakularny budynek zawieszony nad dawną elektrownią Podgórza. Bezprogowe wejście prosto z placu, panoramiczne windy na kondygnacje wystawowe i kawiarnię z widokiem na Wisłę, system Totupoint dla osób niewidomych.',
      descriptionEn:
          'Architectural marvel hovering over the historic power plant. Ground-level plazas, large elevators to galleries and rooftop cafe overlooking the Vistula, and Totupoint audio beacon system.',
      accessibilityHighlightsPl: [
        'Wejście z poziomu placu miejskiego bez żadnych progów',
        'Nowoczesne windy do zawieszonej galerii i widokowej kawiarni',
        'Elektroniczny system nawigacji dźwiękowej Totupoint',
        'Toalety z certyfikatem bez barier na każdym piętrze',
        '3 dedykowane koperty parkingowe przy Kładce Bernatka',
      ],
      accessibilityHighlightsEn: [
        'Zero-barrier access from urban pedestrian square',
        'Panoramic lifts reaching cantilevered upper galleries and rooftop cafe',
        'Totupoint acoustic beacons for blind visitors',
        'Certified accessible restrooms on all floors',
        '3 reserved parking bays next to Bernatka footbridge',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.cricoteka.pl/',
      instagramUrl: 'https://www.instagram.com/cricoteka/',
      instagramHandle: '@cricoteka',
      facebookUrl: 'https://www.facebook.com/cricoteka',
      facebookName: 'Cricoteka',
      phoneNumber: '+48 12 442 77 70',
    ),

    const AccessiblePlace(
      id: 'place_mos_rajska',
      name: 'Małopolski Ogród Sztuki (MOS)',
      category: AccessiblePlaceCategory.culture,
      categoryLabelPl: 'Centrum sztuki i medioteka bez barier',
      categoryLabelEn: 'Malopolska Garden of Arts',
      address: 'ul. Rajska 12, 31-124 Kraków',
      district: 'Piasek',
      location: LatLng(50.0642, 19.9298),
      accessibilityScore: 97,
      descriptionPl:
          'Wielokrotnie nagradzany budynek łączący teatr, kino studyjne i mediatekę. Pełna dostępność dla wózków (podziemna sala teatralna z windami), pętle indukcyjne oraz stanowiska komputerowe z oprogramowaniem udźwiękawiającym.',
      descriptionEn:
          'Award-winning architectural complex housing theatre, cinema, and media library. Full wheelchair access to underground auditorium, induction hearing loops, and screen reader workstations.',
      accessibilityHighlightsPl: [
        'Podziemna sala teatralna i kinowa w 100% dostępne windą',
        'Pętla indukcyjna na całej powierzchni sali głównej',
        'Stanowiska z programami powiększającymi i czytającymi tekst',
        'Szerokie korytarze i bezprogowe automatyczne przejścia',
        'Darmowy wstęp dla opiekunów osób ze znacznym stopniem niepełnosprawności',
      ],
      accessibilityHighlightsEn: [
        'Underground theatre and cinema completely elevator-accessible',
        'Loop system covering entire main hall floor area',
        'Magnification and screen-reader workstations in media library',
        'Wide corridors and automatic sliding doors throughout',
        'Free admission for registered personal assistants',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://teatrwkrakowie.pl/malopolski-ogrod-sztuki',
      instagramUrl: 'https://www.instagram.com/malopolskiogrodsztuki/',
      instagramHandle: '@malopolskiogrodsztuki',
      facebookUrl: 'https://www.facebook.com/MalopolskiOgrodSztuki',
      facebookName: 'Malopolski Ogrod Sztuki',
      phoneNumber: '+48 12 424 45 40',
    ),

    const AccessiblePlace(
      id: 'place_urzad_miasta',
      name: 'Urząd Miasta Krakowa (Magistrat)',
      category: AccessiblePlaceCategory.publicBuilding,
      categoryLabelPl: 'Urząd z punktem obsługi bez barier',
      categoryLabelEn: 'Accessible City Hall',
      address: 'Plac Wszystkich Świętych 3-4, 31-004 Kraków',
      district: 'Stare Miasto',
      location: LatLng(50.0589, 19.9382),
      accessibilityScore: 96,
      descriptionPl:
          'Zabytkowy Pałac Wielopolskich dostosowany do sprawnej obsługi mieszkańców. Wejście z podnośnikiem, Punkt Obsługi Osób z Niepełnosprawnościami na parterze, wideotłumacz Polskiego Języka Migowego online oraz pętla indukcyjna.',
      descriptionEn:
          'Historic City Hall adapted for comprehensive civic access. Ground-floor accessibility desk, certified Polish Sign Language video interpreter on demand, hearing loops, and Totupoint audio guidance.',
      accessibilityHighlightsPl: [
        'Punkt Obsługi Osób z Niepełnosprawnościami na parterze budynku',
        'Stanowisko z wideotłumaczem Polskiego Języka Migowego (PJM) na żywo',
        'Pętla indukcyjna na głównych stanowiskach obsługi interesanta',
        'Dźwiękowy system nawigacji miejskiej Totupoint',
        '4 dedykowane koperty parkingowe na dziedzińcu magistratu',
      ],
      accessibilityHighlightsEn: [
        'Dedicated Special Needs Civic Service Desk on ground level',
        'Live Polish Sign Language (PJM) online remote video interpreter',
        'Induction hearing loops at all public service counters',
        'Totupoint acoustic wayfinding beacon at building entrance',
        '4 reserved accessible parking spots inside City Hall courtyard',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.bip.krakow.pl/',
      instagramUrl: 'https://www.instagram.com/krakow_pl/',
      instagramHandle: '@krakow_pl',
      facebookUrl: 'https://www.facebook.com/krakow.pl',
      facebookName: 'Krakow PL (Oficjalny profil miasta)',
      phoneNumber: '+48 12 616 12 00',
    ),

    const AccessiblePlace(
      id: 'place_biblioteka_rajska',
      name: 'Wojewódzka Biblioteka Publiczna w Krakowie',
      category: AccessiblePlaceCategory.publicBuilding,
      categoryLabelPl: 'Biblioteka z działem tyflologicznym',
      categoryLabelEn: 'Public Library with Braille Dept.',
      address: 'ul. Rajska 1, 31-124 Kraków',
      district: 'Piasek',
      location: LatLng(50.0645, 19.9312),
      accessibilityScore: 97,
      descriptionPl:
          'Jedna z najnowocześniejszych bibliotek w Polsce pod względem dostępności. Dedykowany Dział Zbiorów Tyflologicznych z książkami w alfabecie Braille’a, powiększalnikami tekstu, syntezatorami mowy i klawiaturami wielkoznakowymi.',
      descriptionEn:
          'Premier regional library featuring specialized blindness and low-vision department, audiobooks, Braille collection, electronic desktop magnifiers, and voice-assisted workstations.',
      accessibilityHighlightsPl: [
        'Dział Zbiorów Tyflologicznych ze zbiorem książek Braille’a i audiobooków',
        'Elektroniczne powiększalniki stacjonarne oraz klawiatury wielkoznakowe',
        'Windy przystosowane z komunikatami głosowymi i oznaczeniem pięter w Braille',
        'Rampa wejściowa z poziomu zielonego dziedzińca',
        'Szkolenia cyfrowe z obsługi czytników ekranu dla osób niedowidzących',
      ],
      accessibilityHighlightsEn: [
        'Dedicated Braille & Accessible Audio Lending Department',
        'Electronic text magnifiers and high-contrast oversized keyboards',
        'Lifts with voice prompts and Braille level buttons',
        'Smooth courtyard ramp leading to automatic entrance',
        'Assistive tech digital workshops for visually impaired community',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.rajska.info/',
      instagramUrl: 'https://www.instagram.com/rajska_1/',
      instagramHandle: '@rajska_1',
      facebookUrl: 'https://www.facebook.com/rajska1',
      facebookName: 'Wojewodzka Biblioteka Publiczna w Krakowie',
      phoneNumber: '+48 12 375 22 00',
    ),

    const AccessiblePlace(
      id: 'place_tauron_arena',
      name: 'Tauron Arena Kraków',
      category: AccessiblePlaceCategory.publicBuilding,
      categoryLabelPl: 'Arena widowiskowa bez barier',
      categoryLabelEn: 'Accessible Sports & Entertainment Arena',
      address: 'ul. Stanisława Lema 7, 31-571 Kraków',
      district: 'Czyżyny',
      location: LatLng(50.0682, 19.9905),
      accessibilityScore: 99,
      descriptionPl:
          'Największa hala widowiskowo-sportowa w Polsce. Posiada ponad 60 dedykowanych miejsc dla osób na wózkach wraz z miejscami dla osób towarzyszących, bezprogowe promenady, windy na każdy poziom oraz pętle indukcyjne w punktach informacyjnych.',
      descriptionEn:
          'Largest indoor arena in Poland. Features over 60 dedicated wheelchair vantage spaces with companion seats, step-free concourses, dedicated access gates, and hearing loops.',
      accessibilityHighlightsPl: [
        'Ponad 60 specjalnych miejsc widokowych dla osób na wózkach z towarzyszami',
        'Dedykowane wejście VIP/ON z poziomu promenady bez kolejek',
        'Windy wielkogabarytowe na wszystkie kondygnacje i do lóż',
        'Dostosowane toalety z systemem przywoławczym na każdym sektorze',
        '8 dedykowanych kopert parkingowych bezpośrednio przy bramie wjazdowej',
      ],
      accessibilityHighlightsEn: [
        'Over 60 dedicated elevated wheelchair bays with companion seats',
        'Fast-track accessible entry gate from main concourse',
        'High-capacity elevators serving all levels and private boxes',
        'Accessible restrooms with emergency pull cords across every zone',
        '8 reserved oversized accessible parking spots near entry',
      ],
      hasWheelchairAccess: true,
      hasHearingLoop: true,
      hasBrailleOrAudio: true,
      hasAdaptedRooms: false,
      hasAdaptedRestroom: true,
      hasAssistanceDogWelcome: true,
      hasDedicatedParking: true,
      websiteUrl: 'https://www.tauronarenakrakow.pl/',
      instagramUrl: 'https://www.instagram.com/tauronarenakrakow/',
      instagramHandle: '@tauronarenakrakow',
      facebookUrl: 'https://www.facebook.com/TAURONArenaKrakow',
      facebookName: 'TAURON Arena Kraków',
      phoneNumber: '+48 12 349 11 02',
    ),
  ];

  static List<ParkingSpot> getParkingSpots() {
    return disabledParkingSpots;
  }

  static List<AccessiblePlace> getAccessiblePlaces() {
    return accessiblePlaces;
  }

  static List<AccessiblePlace> getHotels() {
    return accessiblePlaces
        .where((p) => p.category == AccessiblePlaceCategory.hotel)
        .toList();
  }

  static List<AccessiblePlace> getCulturalAndPublicBuildings() {
    return accessiblePlaces
        .where((p) => p.category != AccessiblePlaceCategory.hotel)
        .toList();
  }
}
